# Generated by Django 5.2.12 on 2026-03-30 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['recipe_id', 'ingredient__name']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.FloatField(help_text='Kilocalories per 100 g.'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.FloatField(help_text='Grams of protein per 100 g (0 allowed).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(help_text='Amount of this ingredient in the recipe (grams).'),
        ),
    ]
