# Generated by Django 5.2.12 on 2026-03-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard user'), ('nutrition_coach', 'Nutrition coach')], default='standard', help_text='Standard: meal plans from targets. Nutrition coach: also manages ingredients and recipes.', max_length=20),
        ),
    ]
