# Generated by Django 5.2.12 on 2026-03-30 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Full age helps in sensitive calculation of meal-plan ranges.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_goal',
            field=models.CharField(blank=True, choices=[('lose', 'Lose Weight'), ('maintain', 'Maintain'), ('gain', 'Gain Muscle')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimeters (cm); must be greater than zero.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('standard', 'Standard user'), ('nutrition_coach', 'Nutrition coach')], help_text='Standard user: meal plans from targets. Nutrition coach: also manages ingredients and recipes.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kilograms (kg); must be greater than zero.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
