# Generated by Django 5.2.12 on 2026-03-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_items',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='ingredients.RecipeIngredient', to='ingredients.ingredient'),
        ),
    ]
