# Generated by Django 5.2.12 on 2026-03-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredient_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo of the finished dish.', null=True, upload_to='recipe_images/'),
        ),
    ]
