# Generated by Django 5.2.12 on 2026-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='generation_notice',
            field=models.TextField(blank=True, help_text='Set by the background worker (warnings after target-based generation).'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], db_index=True, default='done', max_length=16),
        ),
    ]
